name: Lab 4 CI Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run a simple script
        run: echo "Hello from GitHub Actions!"
      - name: Break the build
        run: exit 1
